'use strict';
const {VERSION,backendUrl}=require('./_backend');
const {injectV259Runtime}=require('./_ui_runtime_v2523');
let lastGoodHtml='';let lastGoodAt=0;
const TARGET='2.5.23';
function detectedVersion(raw){const m=String(raw||'').match(/V(2\.5\.6\.14|2\.5\.7|2\.5\.8|2\.5\.9|2\.5\.10|2\.5\.11|2\.5\.12|2\.5\.13|2\.5\.20|2\.5\.21|2\.5\.22|2\.5\.23)\s+PERLA ANDINA/i);return m?m[1]:'';}
function validPortalUi(raw){const s=String(raw||'');const directPortal=/id=["']catalog["']/i.test(s)&&/function\s+init\s*\(/.test(s);const googleWrapper=/goog\.script\.init\s*\(|userCodeAppPanel|sandboxFrame/i.test(s);const v=detectedVersion(s);return s.length>50000&&/<html[\s>]/i.test(s)&&/Perla Andina/i.test(s)&&/<body[\s>]/i.test(s)&&directPortal&&!!v&&!googleWrapper;}
function prepareUi(raw){if(!validPortalUi(raw))throw new Error('BACKEND_UI_INVALID');const html=injectV259Runtime(raw);if(!validPortalUi(html)||!html.includes('data-perla-runtime="2523"'))throw new Error('V2523_UI_PATCH_INVALID');return html;}
async function fetchCandidate(url,timeoutMs){const ctrl=new AbortController(),tm=setTimeout(()=>ctrl.abort(),timeoutMs);try{const r=await fetch(url,{method:'GET',redirect:'follow',signal:ctrl.signal,headers:{'user-agent':'Perla-Andina-Vercel/'+VERSION,'cache-control':'no-cache','pragma':'no-cache'}});const raw=await r.text();if(!r.ok)throw new Error('HTTP_'+r.status);if(!validPortalUi(raw))throw new Error('INVALID_UI');return raw;}finally{clearTimeout(tm)}}
async function fetchRawUi(){const BACKEND=backendUrl();if(!BACKEND)throw new Error('B2B_BACKEND_NOT_CONFIGURED');const sep=BACKEND.includes('?')?'&':'?';try{return await fetchCandidate(BACKEND+sep+'raw_ui=1&portal_version=2523',20000)}catch(e){throw new Error('BACKEND_RAW_UI_FAILED '+String(e&&e.message||e))}}
function setPrivateNoStore(res){res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Vercel-CDN-Cache-Control','no-store');}
function setImmutableUiCache(res){res.setHeader('Cache-Control','public, max-age=31536000, immutable');res.setHeader('CDN-Cache-Control','public, s-maxage=31536000, stale-while-revalidate=604800, stale-if-error=2592000');res.setHeader('Vercel-CDN-Cache-Control','public, s-maxage=31536000, stale-while-revalidate=604800');}
module.exports=async function handler(req,res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Perla-Version',VERSION);res.setHeader('X-Perla-Ui-Cache-Key','2523');if(req.method!=='GET'){setPrivateNoStore(res);return res.status(405).send('METHOD_NOT_ALLOWED')}const requested=String(req.query&&req.query.v||'');if(requested&&requested!=='2523'){setPrivateNoStore(res);return res.status(409).send('UI_VERSION_KEY_MISMATCH')}try{const raw=await fetchRawUi();const rawVersion=detectedVersion(raw);const html=prepareUi(raw);lastGoodHtml=html;lastGoodAt=Date.now();if(rawVersion===TARGET)setImmutableUiCache(res);else setPrivateNoStore(res);res.setHeader('X-Perla-Ui-Backend-Version',rawVersion||'unknown');res.setHeader('X-Perla-Ui-Source','apps-script-v2523-runtime');res.setHeader('X-Perla-Ui-Patch','v2523-runtime');res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(html);}catch(err){if(lastGoodHtml){setPrivateNoStore(res);res.setHeader('X-Perla-Ui-Source','memory-last-good');res.setHeader('X-Perla-Ui-Stale-Ms',String(Math.max(0,Date.now()-lastGoodAt)));res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(lastGoodHtml);}setPrivateNoStore(res);return res.status(502).send('B2B_UI_PROXY_FAILED: '+String(err&&err.message||err).slice(0,180));}};
